### ISSUE TITLE
点击存储时报错

### ISSUE THREAD

**Issue by Reviahh** [MaaXYZ/MaaDebugger#10]
### 报错
'NoneType' object has no attribute '_handle'
Traceback (most recent call last):
  File "C:\Users\34907\AppData\Local\Programs\Python\Python311\Lib\site-packages\nicegui\events.py", line 419, in wait_for_result
    await result
  File "C:\Users\34907\AppData\Local\Programs\Python\Python311\Lib\site-packages\MaaDebugger\webpage\index_page\master_control.py", line 337, in on_click_start
    run = await maafw.run_task(entry_input.value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\34907\AppData\Local\Programs\Python\Python311\Lib\site-packages\MaaDebugger\maafw\__init__.py", line 91, in run_task
    self.instance.bind(self.resource, self.controller)
  File "C:\Users\34907\AppData\Local\Programs\Python\Python311\Lib\site-packages\maa\instance.py", line 113, in bind
    Library.framework.MaaBindResource(self._handle, resource._handle)
                                                    ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_handle'

### MaaFw version: v1.8.8
![image](https://github.com/user-attachments/assets/af2319fa-0225-438c-9a2d-b695202eceac)

**Comment by MistEO** [comment]
![image](https://github.com/user-attachments/assets/a0a61e16-385b-4b96-a569-1af79faabb65)

这三个要填的啊，点一下这里 
![image](https://github.com/user-attachments/assets/312d2715-9109-4b53-8060-2c1507d24965)
