### ISSUE TITLE
运行debugger报错

### ISSUE THREAD

**Issue by hdu12** [MaaXYZ/MaaDebugger#11]
![image](https://github.com/user-attachments/assets/6e9de4e6-910d-415d-b2ef-0aa5742da807)
C:\WINDOWS\system32>python -m MaaDebugger
MaaFw version: v1.8.9
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\hdu12\AppData\Local\Programs\Python\Python311\Lib\site-packages\MaaDebugger\__main__.py", line 1, in <module>
    from .main import main
  File "C:\Users\hdu12\AppData\Local\Programs\Python\Python311\Lib\site-packages\MaaDebugger\main.py", line 3, in <module>
    from .webpage import index_page
  File "C:\Users\hdu12\AppData\Local\Programs\Python\Python311\Lib\site-packages\MaaDebugger\webpage\index_page\__init__.py", line 3, in <module>
    from .master_control import main as master_control
  File "C:\Users\hdu12\AppData\Local\Programs\Python\Python311\Lib\site-packages\MaaDebugger\webpage\index_page\master_control.py", line 8, in <module>
    from ...maafw import maafw
  File "C:\Users\hdu12\AppData\Local\Programs\Python\Python311\Lib\site-packages\MaaDebugger\maafw\__init__.py", line 172, in <module>
    maafw = MaaFW()
            ^^^^^^^
  File "C:\Users\hdu12\AppData\Local\Programs\Python\Python311\Lib\site-packages\MaaDebugger\maafw\__init__.py", line 22, in __init__
    Toolkit.init_option("./")
  File "C:\Users\hdu12\AppData\Local\Programs\Python\Python311\Lib\site-packages\maa\toolkit.py", line 34, in init_option
    Library.toolkit.MaaToolkitInitOptionConfig(
OSError: [WinError -529697949] Windows Error 0xe06d7363

C:\WINDOWS\system32>python --version
Python 3.11.9
尝试了3.12也不行，帮忙看一下，谢谢

**Comment by MistEO** [comment]
找个有写权限的目录打开，不能在 system32 下
